### ISSUE TITLE
(Error) Can't open the ZeroNet homepage

### ISSUE THREAD

**Issue by hardBSDk** [ZeroNetX/zeronet-rs#42]
I built this with `cargo build --release` and when I run `cargo run`, the log show this:

```
 INFO  zeronet::plugins::site_server::wrapper > Serving wrapper for zero://1HELLo...2Ri9d/
thread 'actix-rt|system:0|arbiter:0' panicked at src/plugins/site_server/wrapper.rs:81:45:
called `Result::unwrap()` on an `Err` value: WrapperKeyNotFound
 INFO  zeronet::plugins::site_server::wrapper > Serving wrapper for zero://1HELLo...2Ri9d/
thread 'actix-rt|system:0|arbiter:1' panicked at src/plugins/site_server/wrapper.rs:81:45:
called `Result::unwrap()` on an `Err` value: WrapperKeyNotFound
```

**Comment by canewsin** [comment]
fixed v0.2.0
